[fr]: Translations fixes
Laravel-Lang/http-statuses pull request #237
Opened 2024-09-26 08:07 UTC by max13fr

2024-09-26 18:30 UTC, caouecs requested changes

2024-09-26 18:30 UTC, caouecs commented on locales/fr/json.json
> +    "Not Implemented": "Pas implémenté",
Non implémenté(e) ?

2024-09-26 18:30 UTC, caouecs commented on locales/fr/json.json
> +    "Web Server is Down": "Le serveur web est en panne"
je resterais sur Web

2024-09-26 18:30 UTC, caouecs commented on locales/fr/php.json
> +    "501": "Pas implémenté",
Non implémenté ?

2024-09-26 18:30 UTC, caouecs commented on locales/fr/php.json
> +    "502": "Passerelle invalide",
L'erreur 502 est "Bad Gateway ou Proxy Error", c'est donc un mix des deux propositions de traduction

2024-09-26 18:30 UTC, caouecs commented on locales/fr/php.json
> +    "521": "Le serveur web est en panne",
je resterais sur Web

2024-09-26 19:43 UTC, max13fr commented
Fixed everything, thanks for the review

2024-09-30 19:03 UTC, caouecs approved these changes

2024-09-30 19:55 UTC, andrey-helldar approved these changes
Merci

2024-09-30 19:55 UTC, merged